[package]
name = "sparrow"
version = "0.1.0"
edition = "2024"
default-run = "main"

[features]
live_svg = []
only_final_svg = []

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"

[[bin]]
name = "overlap_visualizer"
path = "src/util/playgrounds/playground_overlap_visualizer.rs"

[[bin]]
name = "paper"
path = "src/util/playgrounds/playground_paper.rs"

[dependencies]
jagua-rs = { path = "libs/jagua-rs/jagua-rs"}
rand = { version = "0.9.0", features = [ "small_rng" ] }
rand_distr = "0.5.1"
svg = "0.18.0"
itertools = "0.14.0"
log = { version = "0.4", features = ["release_max_level_info"] }
fern = "0.7"
serde = "1.0"
serde_json = "1.0"
once_cell = "1.20"
humantime = "2.1.0"
tap = "1.0.1"
slotmap = "1.0"
float-cmp = "0.10.0"
ordered-float = "5.0.0"
rayon = "1.10.0"
numfmt = "1.1.1"
plotly = "0.12.1"
num_cpus = "1.16.0"
chrono = "0.4"
ctrlc = "3.4.5"

[profile.dev]
overflow-checks=true

[profile.test]
inherits = "release"
debug-assertions = true
debug = true

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1
panic = "abort"