name: extra benches (on 5950X)

on:
  workflow_dispatch:
    inputs:
      n_runs:
        description: 'Number of times to run each instance'
        default: 16
        required: true
        type: number
      run_time_s:
        description: 'Time per run in seconds'
        default: 1200
        required: true
        type: number

jobs:
  benchmark:
    runs-on: [ self-hosted,5950X ]
    strategy:
      matrix:
        instance: [ "blaz1", "fu", "jakobs1", "jakobs2","shapes0", "shapes1" ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@stable

      - name: Run bench for ${{ matrix.instance }}
        env:
          RUSTFLAGS: '-C target-cpu=native -Awarnings' #disable warnings and optimize for the host CPU
        run: |
          echo RUSTFLAGS=$RUSTFLAGS
          output=$(cargo run --profile release-ultimate --bin bench -- libs/jagua-rs/assets/${{ matrix.instance }}.json ${{ github.event.inputs.run_time_s}} ${{ github.event.inputs.n_runs }} | tee /dev/stderr)

          # Write to log file
          echo "$output" > "output/${{ matrix.instance }}_bench_stdout.log"

          {
            echo "## Benchmark Output for \`${{ matrix.instance }}\`"
            echo '```'
            echo "$output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Compress output folder for ${{ matrix.instance }}
        run: |
          mv output/ output_${{ matrix.instance }}
          tar -czf ${{ matrix.instance }}_output.tar.gz output_${{ matrix.instance }}

      - name: Upload artifact for ${{ matrix.instance }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.instance }}-results
          path: ${{ matrix.instance }}_output.tar.gz
          retention-days: 7