name: main benches

on:
  workflow_dispatch:
    inputs:
      n_runs:
        description: 'Number of times to run each instance'
        default: 16
        required: true
        type: number
      run_time_s:
        description: 'Time per run in seconds'
        default: 1200
        required: true
        type: number
      cpu_tag:
        description: 'CPU type for runner (5950X, 7950X)'
        required: true
        type: choice
        options:
          - 5950X
          - 7950X
          - 9950X

jobs:
  swim:
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: swim
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}

  trousers:
    needs: swim
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: trousers
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}

  shirts:
    needs: trousers
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: shirts
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}

  mao:
    needs: shirts
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: mao
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}

  dagli:
    needs: mao
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: dagli
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}

  albano:
    needs: dagli
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: albano
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}

  marques:
    needs: albano
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: marques
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}