name: nightly benches

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
  push:
    branches:
      - exp/*

env:
  N_RUNS: 16
  RUN_TIME_S: 1200   
  CPU_TAG: 5950X  

jobs:
  swim:
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: swim
      n_runs: $N_RUNS
      run_time_s: $RUN_TIME_S
      cpu_tag: $CPU_TAG

  trousers:
    needs: swim
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: trousers
      n_runs: $N_RUNS
      run_time_s: $RUN_TIME_S
      cpu_tag: $CPU_TAG

  shirts:
    needs: trousers
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: shirts
      n_runs: $N_RUNS
      run_time_s: $RUN_TIME_S
      cpu_tag: $CPU_TAG

  mao:
    needs: shirts
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: mao
      n_runs: $N_RUNS
      run_time_s: $RUN_TIME_S
      cpu_tag: $CPU_TAG

  dagli:
    needs: mao
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: dagli
      n_runs: $N_RUNS
      run_time_s: $RUN_TIME_S
      cpu_tag: $CPU_TAG

  albano:
    needs: dagli
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: albano
      n_runs: $N_RUNS
      run_time_s: $RUN_TIME_S
      cpu_tag: $CPU_TAG

  marques:
    needs: albano
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: marques
      n_runs: $N_RUNS
      run_time_s: $RUN_TIME_S
      cpu_tag: $CPU_TAG