name: nightly benches

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
  push:
    branches:
      - exp/*

jobs:
  benchmark:
    runs-on: [self-hosted,5950X]
    strategy:
      matrix:
        instance: ["swim", "trousers", "shirts", "albano", "mao", "dagli", "marques"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@stable

      - name: Disable compiler warnings
        run: echo "RUSTFLAGS=-Awarnings" >> $GITHUB_ENV

      - name: Run nightly bench for ${{ matrix.instance }}
        run: |
          output=$(cargo run --release --bin nightly_benchmark -- libs/jagua-rs/assets/${{ matrix.instance }}.json)
          
          echo "$output"
          
          {
            echo "## Benchmark Output for \`${{ matrix.instance }}\`"
            echo '```'
            echo "$output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
