name: nightly benches

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
  push:
    branches:
      - exp/*

jobs:
  benchmark:
    runs-on: [ self-hosted,5950X ]
    strategy:
      matrix:
        instance: [ "marques", "dagli", "albano", "mao","shirts", "trousers", "swim" ]
        n_runs: [ 16 ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@stable

      - name: Disable compiler warnings
        run: echo "RUSTFLAGS=-Awarnings" >> $GITHUB_ENV

      - name: Run bench for ${{ matrix.instance }}
        run: |
          output=$(cargo run --profile release-ultimate --bin benchmark -- ${{ matrix.n_runs }} libs/jagua-rs/assets/${{ matrix.instance }}.json | tee /dev/stderr)
          
          {
            echo "## Benchmark Output for \`${{ matrix.instance }}\`"
            echo '```'
            echo "$output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
