name: nightly benches

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
  push:
    branches:
      - exp/*

jobs:
  benchmark:
    runs-on: [ self-hosted,5950X ]
    strategy:
      matrix:
        instance: [ "marques", "dagli", "albano", "mao","shirts", "trousers", "swim" ]
        n_runs: [ 16 ]
        run_time_s: [ 1200 ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@stable

      - name: Run bench for ${{ matrix.instance }}
        env:
          RUSTFLAGS: '-C target-cpu=native -Awarnings'
        run: |
          output=$(cargo run --profile release-ultimate --bin bench -- libs/jagua-rs/assets/${{ matrix.instance }}.json ${{ matrix.run_time_s}} ${{ matrix.n_runs }} | tee /dev/stderr)
          
          # Write to log file
          echo "$output" > "output/${{ matrix.instance }}_bench_stdout.log"
          
          {
            echo "## Benchmark Output for \`${{ matrix.instance }}\`"
            echo '```'
            echo "$output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Compress output folder for ${{ matrix.instance }}
        run: |
          mv output/ output_${{ matrix.instance }}
          tar -czf ${{ matrix.instance }}_output.tar.gz output_${{ matrix.instance }}

      - name: Upload artifact for ${{ matrix.instance }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.instance }}-results
          path: ${{ matrix.instance }}_output.tar.gz
          retention-days: 7