name: Nightly Benchmarks

on:
  # Run once a day at 01:00 UTC (adjust as needed)
  schedule:
    - cron: '0 1 * * *'
  # Allows you to manually trigger the workflow if needed
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: [self-hosted,5950X]
    strategy:
      matrix:
        instance: ["swim", "trousers", "shirts", "albano", "mao", "dagli", "marques"]

    steps:
      - name: Checkout latest main commit
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: 'recursive'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run benchmark for ${{ matrix.instance }}
        run: cd gls_strip_packing && cargo run --release --bin nightly_benchmark -- ../jagua-rs/assets/${{ matrix.instance }}.json
