name: Nightly Benchmarks

on:
  # Run once a day at 23:00 UTC (0:00 CEST)
  schedule:
    - cron: '2 3 * * *'
  # Allows manually trigger the workflow if needed
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: [self-hosted,5950X]
    strategy:
      matrix:
        instance: ["swim", "trousers", "shirts", "albano", "mao", "dagli", "marques"]

    steps:
      - name: Checkout latest main commit
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: 'recursive'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Disable compiler warnings
        run: echo "RUSTFLAGS=-Awarnings" >> $GITHUB_ENV

      - name: Run nightly_benchmark for ${{ matrix.instance }}
        run: |
          echo $RUSTFLAGS
          cd gls_strip_packing
          cargo run --release --bin nightly_benchmark -- ../jagua-rs/assets/${{ matrix.instance }}.json >> $GITHUB_OUTPUT