name: real benches

on:
  workflow_dispatch:
    inputs:
      n_runs:
        description: 'Number of times to run each instance'
        default: 16
        required: true
        type: number
      run_time_s:
        description: 'Time per run in seconds'
        default: 1200
        required: true
        type: number

jobs:
  benchmark:
    runs-on: [self-hosted,7950X]
    strategy:
      matrix:
        instance: [ "marques", "dagli", "albano", "mao","shirts", "trousers", "swim" ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@stable

      - name: Disable compiler warnings
        run: echo "RUSTFLAGS=-Awarnings" >> $GITHUB_ENV

      - name: Run bench for ${{ matrix.instance }}
        run: |
          output=$(cargo run --profile release-ultimate --bin bench -- ${{ github.event.inputs.n_runs }} libs/jagua-rs/assets/${{ matrix.instance }}.json ${{ github.event.inputs.run_time_s}} | tee /dev/stderr)
          
          # Write to log file
          echo "$output" > "output/${{ matrix.instance }}_bench_stdout.log"

          {
            echo "## Benchmark Output for \`${{ matrix.instance }}\`"
            echo '```'
            echo "$output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Compress output folder for ${{ matrix.instance }}
        run: |
          mv output/ output_${{ matrix.instance }}
          tar -czf ${{ matrix.instance }}_output.tar.gz output_${{ matrix.instance }}
      
      - name: Upload artifact for ${{ matrix.instance }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.instance }}-results
          path: ${{ matrix.instance }}_output.tar.gz
          retention-days: 14