name: real benches

on:
  workflow_dispatch:
    inputs:
      n_runs:
        description: 'Number of times to run each instance'
        default: 16
        required: true
        type: number

jobs:
  benchmark:
    runs-on: [self-hosted,7950X]
    strategy:
      matrix:
        instance: [ "marques", "dagli", "albano", "mao","shirts", "trousers", "swim" ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@stable

      - name: Disable compiler warnings
        run: echo "RUSTFLAGS=-Awarnings" >> $GITHUB_ENV

      - name: Run bench for ${{ matrix.instance }}
        run: |
          output=$(cargo run --profile release-ultimate --bin benchmark -- ${{ github.event.inputs.n_runs }} libs/jagua-rs/assets/${{ matrix.instance }}.json | tee /dev/stderr)
          
          {
            echo "## Benchmark Output for \`${{ matrix.instance }}\`"
            echo '```'
            echo "$output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
