name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'
#  pull_request:
#    branches: [ "main" ]
#    paths:
#      - '**.rs'
#      - '**.toml'
#      - '**.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Run tests (no SIMD)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: rustup toolchain install stable --profile minimal && rustup default stable
      - run: cargo test

  tests-simd:
    name: Run tests (SIMD)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: rustup toolchain install nightly --profile minimal && rustup default nightly
      - run: cargo test --features=simd