name: single bench

on:
  workflow_call:
    inputs:
      instance:
        required: true
        type: string
      n_runs:
        required: true
        type: number
      run_time_s:
        required: true
        type: number
      cpu_tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      instance:
        description: 'Instance'
        required: true
        type: choice
        options: [ swim, trousers, shirts, mao, dagli, albano, marques, blaz1, fu, shapes0, shapes1, jakobs1, jakobs2 ]
      n_runs:
        description: 'Number of times to run the instance'
        default: 16
        required: true
        type: number
      run_time_s:
        description: 'Time per run in seconds'
        default: 1200
        required: true
        type: number
      cpu_tag:
        description: 'CPU type for job'
        required: true
        type: choice
        options:
          - 5950X
          - 7950X
          - 9950X

jobs:
  run-benchmark:
    name: bench ${{ inputs.instance }} (${{ inputs.n_runs }} x ${{ inputs.run_time_s }}s)
    runs-on: ${{ inputs.cpu_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@nightly
      - name: Run bench for ${{ inputs.instance }}
        env:
          RUSTFLAGS: '-C target-cpu=native -Awarnings'
        run: |
          export RUSTFLAGS=$RUSTFLAGS
          output=$(cargo run --profile release --features=only_final_svg,simd --bin bench -- data/input/${{ inputs.instance }}.json ${{ inputs.run_time_s}} ${{ inputs.n_runs }} | tee /dev/stderr)
          echo "$output" > "output/${{ inputs.instance }}_bench_stdout.log"
          {
            echo "## Benchmark Output for \`${{ inputs.instance }}\`"
            echo '```'
            echo "$output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Compress output folder
        run: |
          mv output/ output_${{ inputs.instance }}
          tar -czf ${{ inputs.instance }}_output.tar.gz output_${{ inputs.instance }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.instance }}-results
          path: ${{ inputs.instance }}_output.tar.gz
          retention-days: 14